package simpledb.execution;

import simpledb.transaction.TransactionAbortedException;
import simpledb.common.DbException;
import simpledb.storage.Tuple;
import simpledb.storage.TupleDesc;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;
    private final JoinPredicate p;
    private OpIterator child1;
    private OpIterator child2;
    private Tuple currChild1;

    /**
     * Constructor. Accepts two children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, OpIterator child1, OpIterator child2) {
        // some code goes here
        this.p = p;
        this.child1 = child1;
        this.child2 = child2;
        this.currChild1 = null;
    }

    public JoinPredicate getJoinPredicate() {
        // some code goes here
        return this.p;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        // some code goes here
        StringBuilder sb = new StringBuilder();
        return child1.getTupleDesc().getFieldName(p.getField1());
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        // some code goes here
        return child2.getTupleDesc().getFieldName(p.getField2());
    }

    /**
     * @see TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        // some code goes here
        return TupleDesc.merge(child1.getTupleDesc(), child2.getTupleDesc());
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // some code goes here
        super.open();
        child1.open();
        child2.open();
        if (child1.hasNext()) currChild1 = child1.next();
    }

    public void close() {
        // some code goes here
        this.currChild1 = null;
        this.child2.close();
        this.child1.close();
        super.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // some code goes here
        this.close();
        this.open();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // some code goes here
        if (noRemainingTuples()) return null;
        while (!noRemainingTuples()) {
            /* if child2 at end */
            if (!child2.hasNext()) {
                /* update child1 and reset child2 to the start */
                currChild1 = child1.next();
                child2.rewind();
                Tuple t2 = child2.next();
                if (p.filter(currChild1, t2)) {
                    return addUpTuple(currChild1, t2);
                } else {
                    continue;
                }
            }
            /* no need to update child1 */
            Tuple t2 = child2.next();
            if (p.filter(currChild1, t2)) {
                return addUpTuple(currChild1, t2);
            }
        }
        return null;
    }

    private boolean noRemainingTuples() throws TransactionAbortedException, DbException {
        return !child2.hasNext() && !child1.hasNext();
    }

    private Tuple addUpTuple(Tuple t1, Tuple t2) {
        Tuple res = new Tuple(this.getTupleDesc());
        int numFieldsChild1 = t1.getTupleDesc().numFields();
        int numFieldsChild2 = t2.getTupleDesc().numFields();
        for (int i = 0; i < numFieldsChild1; i++) {
            res.setField(i, t1.getField(i));
        }
        for (int i = numFieldsChild1; i < numFieldsChild2 + numFieldsChild1; i++) {
            res.setField(i, t2.getField(i - numFieldsChild1));
        }
        return res;
    }

    @Override
    public OpIterator[] getChildren() {
        // some code goes here
        return new OpIterator[]{this.child1, this.child2};
    }

    @Override
    public void setChildren(OpIterator[] children) {
        // some code goes here
        this.child1 = children[0];
        this.child2 = children[1];
    }

}
